# .woodpecker.yml
steps:
  - name: build-ssr-production
    image: node:22
    volumes:
      - /home/www/public/doger:/app/dist
    commands:
      - npm ci
      - npm run build:production
      - mkdir -p /home/www/public/doger
      - cp -r dist/dogger/browser/* /home/www/public/doger/
      - cp -r dist/dogger/server /home/www/public/doger/
      - ls -la /home/www/public/doger
      - ls -la /home/www/public/doger/server
    when:
      - branch: master
      - event: push