# .woodpecker.yml
name: Dogger Production Build

steps:
  - name: build-production
    image: node:18
    volumes:
      - /builds:/app/dist
    commands:
      - npm ci
      - npm run build:production
      - mkdir -p /builds/dogger
      - cp -r dist/dogger/* /builds/dogger/
      - ls -la /builds/dogger/
    when:
      - branch: master
      - event: push