# .woodpecker.yml
steps:
  - name: build-production
    image: node:22
    volumes:
      - /home/www/public/doger:/app/dist
    commands:
      - npm ci
      - npm run build:production
      - mkdir -p /builds/dogger
      - cp -r dist/dogger/* /home/www/public/doger
      - ls -la /home/www/public/doger
    when:
      - branch: master
      - event: push