# .woodpecker.yml
steps:
  - name: build
    image: node:22-alpine
    commands:
      - echo "=== Variables de entorno de Woodpecker ==="
      - echo "CI_WORKSPACE=$CI_WORKSPACE"
      - echo "CI_REPO=$CI_REPO"
      - echo "CI_REPO_OWNER=$CI_REPO_OWNER"
      - echo "CI_REPO_NAME=$CI_REPO_NAME"
      - echo "CI_COMMIT_SHA=$CI_COMMIT_SHA"
      - echo "CI_COMMIT_BRANCH=$CI_COMMIT_BRANCH"
      - echo "CI_COMMIT_MESSAGE=$CI_COMMIT_MESSAGE"
      - echo "CI_COMMIT_AUTHOR=$CI_COMMIT_AUTHOR"
      - echo "=========================================="
      - pwd
      - ls -la
      - apk add --no-cache python3 make g++
      - npm ci --silent --no-audit --no-fund
      - npm run build:production
      - echo "Build completado exitosamente!"
      - ls -la dist/dogger/
    when:
      - branch: master
      - event: push

  - name: deploy
    image: alpine:latest
    commands:
      - echo "=== Preparando despliegue ==="
      - mkdir -p /deploy/dogger-front
      - cp -r dist/dogger/* /deploy/dogger-front/
      - echo "Archivos copiados a /deploy/dogger-front"
      - ls -la /deploy/dogger-front/
    volumes:
      - /var/www/dogger:/deploy/dogger-front
    when:
      - branch: master
      - event: push